"""add_spotify_top5_to_albums

Revision ID: 4ee1b42d7212
Revises: d63cc99c8b3f
Create Date: 2026-05-15 15:45:32.920030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee1b42d7212'
down_revision: Union[str, Sequence[str], None] = 'd63cc99c8b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_top5_indices', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_column('spotify_top5_indices')

    # ### end Alembic commands ###
