"""add_albums_tracks_baseline_stats

Revision ID: 9f640281c8b1
Revises: ef275ba19e1c
Create Date: 2026-05-14 15:54:59.181349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f640281c8b1'
down_revision: Union[str, Sequence[str], None] = 'ef275ba19e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('release_date', sa.String(length=20), nullable=False),
    sa.Column('total_songs', sa.Integer(), nullable=False),
    sa.Column('album_art_url', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_albums_spotify_id'), ['spotify_id'], unique=True)

    op.create_table('baseline_stats',
    sa.Column('k', sa.Integer(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('std', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('album_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('spotify_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('album_id', 'index', name='uq_album_track_index')
    )
    with op.batch_alter_table('album_tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_album_tracks_album_id'), ['album_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album_tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_album_tracks_album_id'))

    op.drop_table('album_tracks')
    op.drop_table('baseline_stats')
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_albums_spotify_id'))

    op.drop_table('albums')
    # ### end Alembic commands ###
