"""add_friendships

Revision ID: c08ff9961194
Revises: 4ee1b42d7212
Create Date: 2026-05-15 16:28:42.421616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c08ff9961194'
down_revision: Union[str, Sequence[str], None] = '4ee1b42d7212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_a_username', sa.String(length=30), nullable=False),
    sa.Column('user_b_username', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', name='friendshipstatus'), nullable=False),
    sa.Column('requested_by', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('user_a_username < user_b_username', name='ck_friendship_ordered_pair'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.username'], ),
    sa.ForeignKeyConstraint(['user_a_username'], ['users.username'], ),
    sa.ForeignKeyConstraint(['user_b_username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_a_username', 'user_b_username', name='uq_friendship_pair')
    )
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friendships_user_a_username'), ['user_a_username'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_user_b_username'), ['user_b_username'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendships_user_b_username'))
        batch_op.drop_index(batch_op.f('ix_friendships_user_a_username'))

    op.drop_table('friendships')
    # ### end Alembic commands ###
