"""add_ratings_song_notes

Revision ID: d63cc99c8b3f
Revises: 9f640281c8b1
Create Date: 2026-05-14 19:22:50.473037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63cc99c8b3f'
down_revision: Union[str, Sequence[str], None] = '9f640281c8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('top_track_indices', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', name='ratingstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_edited_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'album_id', name='uq_rating_user_album')
    )
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ratings_album_id'), ['album_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_username'), ['username'], unique=False)

    op.create_table('song_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('track_index', sa.Integer(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['rating_id'], ['ratings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rating_id', 'track_index', name='uq_song_note_rating_track')
    )
    with op.batch_alter_table('song_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_song_notes_rating_id'), ['rating_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_notes_rating_id'))

    op.drop_table('song_notes')
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratings_username'))
        batch_op.drop_index(batch_op.f('ix_ratings_album_id'))

    op.drop_table('ratings')
    # ### end Alembic commands ###
